server: 
  port: 8003
eureka:
  client:
      service-url:
        defaultZone: http://localhost:8000/eureka/
      fetch-registry: true
      registry-fetch-interval-seconds: 10
  instance:
      prefer-ip-address: true
      appname: rujianbin-graydeploy-consumer
spring:
  application:
    name: rujianbin-graydeploy-consumer

logging:
  level:
    rujianbin:
      service:
        IConsumerHelloService: DEBUG

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD    #THREAD  SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

rujianbin:
  testName: local-safwer2
#graybunny:
#  instance:
#    grayEnroll: true #是否在启动后自动注册成灰度实例
#  serverUrl: http://localhost:8001 #灰度服务端的url


    
    
    
    
    