spring:
  application:
    name: rujianbin-graydeploy-provider
server:
  port: 8002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
    metadata-map:
      versions: 1.0

#graybunny:
#  instance:
#    grayEnroll: false